language: go

go: 
  - tip
  - 1.6.0
  - 1.5.3
  - 1.4.3

install:
  - go get github.com/astaxie/beego
  - go get github.com/patrickmn/go-cache
  - github.com/smartystreets/goconvey/convey

script:
  - go test -v tests/*

notifications:
  email:
    - shubhodeep9@gmail.com