language: go

go:
  - 1.6
  - 1.5.3
  - 1.4.3

go_import_path: go-MyVIT

install:
  - go get github.com/tools/godep
  - go get github.com/smartystreets/goconvey
  - godep get

script:
  - go test -v tests/*

notifications:
  email:
    - ujjwal@ayyangar.net
    - shubhodeep9@gmail.com
